version: '3.4'

services:
  
  auth:
    container_name: AuthService
    build: ./DockerApp/
    env_file: ./DockerApp/Dockerfile.env
    environment:
      - MAIL_SERVER=1000.10000.10000.10000
      - ASPNETCORE_ENVIRONMENT=Debug
      - TEST=TESTWASCOMPLETED