version: '3.4'

services:
  
  api:
    build: ./AuthService/
    env_file: ./AuthService/Env.env
    environment:
      - MAIL_SERVER=1000.10000.10000.10000
      - ASPNETCORE_ENVIRONMENT=Debug
      - TEST=TESTWASCOMPLETED