version: '3.4'

services:
  
  api:
    build: ./
    env_file: ./Dockerfile.env
    environment:
      - MAIL_SERVER=1000.10000.10000.10000
      - ASPNETCORE_ENVIRONMENT=Debug
      - TEST=TESTWASCOMPLETED